### ISSUE TITLE
Open source demo video version?

### ISSUE THREAD

**Issue by mhkeller** [Prinzhorn/better-svelte-virtual-list#1]
Hey Alexander, thanks for making this – I've wanted a component like this that I could use for displaying tables. The version you have in the video in the readme looks great. The column sizing and resizing looks really useful. Are you planning on – or would you be able to – share that demo code?

**Comment by Prinzhorn** [comment]
> Hey Alexander, thanks for making this [...] The version you have in the video in the readme looks great.

You're welcome and thanks!

>  Are you planning on – or would you be able to – share that demo code?

I'm not planning to open-source that, it's part of a commercial product I'm working on. It is also very specific to my use-case, so I won't go through the work to make it a general purpose grid library. I'm not interested in maintaining something like this right now. I've built this because none of the existing libraries even closely offer the performance and flexibility I needed.

But the `VirtualList.svelte` is 95% identical to what is used in the video but my wrapping component is different. What is missing is:

1. Each row uses `inline-grid` instead of `inline-block` in this repo. The column sizes are CSS variables on the parent (they come from a Svelte store that is backed by a persistent store).
2. I have a general purpose `resizableHandle` Svelte action that I used for dragging the row separator in the video and other elements in my app
3. The dragging updates the CSS variable on the parent for that particular column. So that all `inline-grid` rows update in unison. That means the whole thing is literally a single ```container.style.setProperty(cssVar, `${width}px`);``` and grid handles the rest
